---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
{{- /*# Iterate over each route to render the routing rules */}}
{{- range $i, $version := .Values.services.reviews.versions }}    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v{{$version}}
  labels:
    app: reviews
    version: v{{$version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v{{$version}}
  template:
    metadata:
      labels:
        app: reviews
        version: v{{$version}}
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v{{ $version }}:1.15.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
{{- end }}